name: ci
on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - container-update

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vibe-documentation repo
        uses: actions/checkout@v4
        with:
          path: ./vibe-documentation
      - name: Checkout the vibe-applications-dev repo
        uses: actions/checkout@v4
        with:
          repository: dsl-unibe-ch/vibe-applications-dev
          path: ./vibe-applications
          token: ${{ secrets.VIBE_APPLICATION_DEV_TOKEN }}
      - name: Create the vibe-documentation/docs/vibe-applications/container/ folder
        run: mkdir -p ./vibe-documentation/docs/vibe-applications/container/
      - name: Copy the container readme files
        run: for file in $(find ./vibe-applications/*/* -iname README.md); do container_name=$(dirname $file | cut -d '/' -f4); cp $file ./vibe-documentation/docs/vibe-applications/container/$container_name.md && echo "* [$container_name]($container_name.md)" >> ./vibe-documentation/docs/vibe-applications/container/SUMMARY.md; done
      - name: Setup the python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install mkdocs material theme
        run: cd vibe-documentation/ && pip install mkdocs-material
      - name: Install required mkdocs plugin 
        run: cd vibe-documentation/ && pip install mkdocs-git-revision-date-plugin mkdocs-literate-nav
      - name: Run the deployment
        run: cd vibe-documentation/ && mkdocs gh-deploy --force
